version: "3"
services:
  web:
    build: .
    ports:
      - "80:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${APP_HOST}"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"