version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${APP_HOST}"
      traefik.frontend.entryPoints: "https"
      traefik.protocol: "https"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.port: "3000"
      traefik.docker.network: "proxy"      
    networks: 
      - proxy
networks:
  proxy:
    external: true