version: "3"
services:
  web:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${APP_HOST}"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"