version: "3"
services:
  web:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    labels:
      traefik.docker.network: "proxy"     
      traefik.enable: "true"
      traefik.frontend.rule: Host:${APP_HOST},www.${APP_HOST}
      traefik.frontend.redirect.regex: ^https?://www.${APP_HOST}/(.*)
      traefik.frontend.redirect.replacement: https://${APP_HOST}/$${1}
      traefik.frontend.redirect.permanent: "true"
      traefik.frontend.entryPoints: "http,https"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.port: "3000" 
    networks: 
      - proxy
networks:
  proxy:
    external: true