version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${APP_HOST}"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
      
    networks: 
      - proxy
